 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/attractions", type: :request do
  # Attraction. As you add validations to Attraction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Attraction.create! valid_attributes
      get attractions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      attraction = Attraction.create! valid_attributes
      get attraction_url(attraction)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_attraction_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      attraction = Attraction.create! valid_attributes
      get edit_attraction_url(attraction)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Attraction" do
        expect {
          post attractions_url, params: { attraction: valid_attributes }
        }.to change(Attraction, :count).by(1)
      end

      it "redirects to the created attraction" do
        post attractions_url, params: { attraction: valid_attributes }
        expect(response).to redirect_to(attraction_url(Attraction.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Attraction" do
        expect {
          post attractions_url, params: { attraction: invalid_attributes }
        }.to change(Attraction, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post attractions_url, params: { attraction: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested attraction" do
        attraction = Attraction.create! valid_attributes
        patch attraction_url(attraction), params: { attraction: new_attributes }
        attraction.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the attraction" do
        attraction = Attraction.create! valid_attributes
        patch attraction_url(attraction), params: { attraction: new_attributes }
        attraction.reload
        expect(response).to redirect_to(attraction_url(attraction))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        attraction = Attraction.create! valid_attributes
        patch attraction_url(attraction), params: { attraction: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested attraction" do
      attraction = Attraction.create! valid_attributes
      expect {
        delete attraction_url(attraction)
      }.to change(Attraction, :count).by(-1)
    end

    it "redirects to the attractions list" do
      attraction = Attraction.create! valid_attributes
      delete attraction_url(attraction)
      expect(response).to redirect_to(attractions_url)
    end
  end
end
